package com.thelightphone.plugin

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.ClassKind

class LightSdkProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private var processed = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (processed) return emptyList()
        processed = true

        val initialScreens = resolver
            .getSymbolsWithAnnotation("com.thelightphone.sdk.InitialScreen")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        val entryPoints = resolver
            .getSymbolsWithAnnotation("com.thelightphone.sdk.EntryPoint")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        // Validate @InitialScreen
        if (initialScreens.size > 1) {
            logger.error(
                "@InitialScreen must be applied to exactly one class. Found: " +
                initialScreens.joinToString { it.qualifiedName?.asString() ?: "unknown" }
            )
            return emptyList()
        }

        // Validate @EntryPoint
        if (entryPoints.size > 1) {
            logger.error(
                "@EntryPoint must be applied to exactly one object. Found: " +
                entryPoints.joinToString { it.qualifiedName?.asString() ?: "unknown" }
            )
            return emptyList()
        }

        entryPoints.firstOrNull()?.let { ep ->
            if (ep.classKind != ClassKind.OBJECT) {
                logger.error("@EntryPoint must be applied to an object, not a class: ${ep.qualifiedName?.asString()}")
                return emptyList()
            }
        }

        val initialScreenFqcn = initialScreens.firstOrNull()?.qualifiedName?.asString()
        val entryPointFqcn = entryPoints.firstOrNull()?.qualifiedName?.asString()

        // Collect all source files that contributed
        val allFiles = (initialScreens + entryPoints).mapNotNull { it.containingFile }

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true, *allFiles.toTypedArray()),
            packageName = "com.thelightphone.sdk.generated",
            fileName = "LightSdkRegistry"
        )

        file.bufferedWriter().use { writer ->
            writer.write(buildString {
                appendLine("package com.thelightphone.sdk.generated")
                appendLine()
                appendLine("// Generated by LightSdkProcessor — do not edit")
                appendLine("object LightSdkRegistry {")
                if (initialScreenFqcn != null) {
                    appendLine("    val initialScreenFactory: (com.thelightphone.sdk.SealedLightActivity) -> com.thelightphone.sdk.SimpleLightScreen = { $initialScreenFqcn(it) }")
                } else {
                    appendLine("    val initialScreenFactory: ((com.thelightphone.sdk.SealedLightActivity) -> com.thelightphone.sdk.SimpleLightScreen)? = null")
                }
                if (entryPointFqcn != null) {
                    appendLine("    val entryPoint: com.thelightphone.sdk.LightEntryPoint = $entryPointFqcn")
                } else {
                    appendLine("    val entryPoint: com.thelightphone.sdk.LightEntryPoint? = null")
                }
                appendLine("}")
            })
        }

        return emptyList()
    }
}

class LightSdkProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return LightSdkProcessor(environment.codeGenerator, environment.logger)
    }
}
